#messages

#get messages 
http://localhost:5000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFzaCIsInJvbGVzIjpbMjAwMV19LCJpYXQiOjE2ODE2NzM2MTIsImV4cCI6MTY4MTY3NzIxMn0.oacZ8E_FLsMS8RPCcWqnoInbXoLZlv3uI7YuVr4XBg4
GET /chat

#post message 
http://localhost:5000
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6ImFzaCIsInJvbGVzIjpbMjAwMV19LCJpYXQiOjE2ODE2NzM2MTIsImV4cCI6MTY4MTY3NzIxMn0.oacZ8E_FLsMS8RPCcWqnoInbXoLZlv3uI7YuVr4XBg4
POST /chat
{
  "text":"hi im cool",
  "sender":"643987a6ffa43719a5ee9b69"
}

